spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/hotel?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: yubin3869
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:db/schema.sql
  application:
    name: hotelSystem

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.studb.entity
  configuration:
    map-underscore-to-camel-case: true